メモアプリコマンドライン版の作成
bore-ko/js-practices pull request #4
Opened 2024-12-07 14:41 UTC by bore-ko

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +class Memo extends FileOperation {
`FileOperation` の子クラスが他にもいて、継承を使うことで子クラス間で処理を共通化できるなら継承を使うのがよいと思いますが、少なくとも現状はそうではないので継承を使うべきではないですね。`Memo` と `FileOperation` という名前の関係的にも継承を使うのは相応しくないと思います。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +    this.displayMemos();
コンストラクタはあくまでオブジェクトの初期化処理を行うものなので、そこに実際に処理まで含めるのはダメですね。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +  }
クラスの外から呼ばれないメソッドはプライベートメソッドにしてください。それとメソッドの定義順を参照順に合わせてください。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +    this.file = "memos.json";
これらのプロパティはクラスの外かアクセスできないようにしてください (カプセル化) 。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +}
`Memo` というクラス名だと 1 件 1 件のメモのデータを扱うものに見えますが、中で定義されているのはメモアプリの処理なのでクラス名が適当ではなさそうです。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +      };
これは何をしているんでしょう...？ 全く意味のない処理に見えます。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +      let memos = await this.read(this.file);
再代入されない変数は `const` を使って宣言してください。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +      let listMemos = firstMemos.join("\n");
いずれの変数も memos とついていますが、格納されているデータの種類がそれぞれ異なるので区別がつかないです。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +      let listMemos = firstMemos.join("\n");
変数名は名詞形になるようにしてください。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +      let firstMemos = memos.map((memo) => memo.body[0]);
`firstMemos` という名前だと何に対する first なのかよく分からないです。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +    const { Select } = pkg;
分割代入する必要は別にないような。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +import pkg from "enquirer";
`pkg` という名前ではプログラム中では何のパッケージだか分からなくなります。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +      message: "Choose a note you want to see:",
メモアプリなので note ではないです。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +
不要な空行が含まれています。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +    prompt.run().catch(console.error);
async/await を使ってください。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +  async add() {
関数中で await が使われていないのに async 関数になっています。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +    });
コールバックではなく Promise として扱えるようにしてください。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +    rl.on("line", (input) => {
`lines` に対応させるなら `input` ではなく `line` だと思います。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +    });
この設定だとパイプでメモを入力したときにその内容が不要に標準出力に出力されます。

![CleanShot 2024-12-25 at 23 05 51@2x](https://github.com/user-attachments/assets/797df205-8bdd-4924-bcd5-dbfbc3754424)

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +      memos.push({ body: lines });
lines は body ではないような。body は本文という意味なので、文字列の配列ではなく文字列が格納されるようなものに使う名前です。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +      let jsonMemos = JSON.stringify(memos, null, "\t");
JSON ファイルのインデントにはタブではなく 2 スペースを使ってください。タブを使うのは一般的ではないです。というのと人間が読む想定でないのであれば読みやすくフォーマットする必要はないと思います (デバッグのためにするなどはしてもよいですが) 。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +      this.write(this.file, jsonMemos);
`write` の返す Promise の完了を待てていないです。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/file_operation.js
> +  async access(file) {
`access` という名前で  boolean が返ってくるのを見通すのは難しい気がします。それと引数として受け取るのはファイルそのものではなくファイル名 (あるいはパス) なので `file` という名前は適当でなさそうです。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/file_operation.js
> +    }
例外が握り潰されています。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/memo.js
> +import * as readline from "readline";
質問ですが、なぜ default import ではなく namespace import しているんでしょうか？

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/file_operation.js
> +      return JSON.parse(data);
`FileOperation` というクラス名でファイルの操作だけをするのであれば、`JSON.parse` まで行うのは `read` メソッドとしてはやりすぎです。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/file_operation.js
> +    }
この実装だと例外が常に再送出されます。

2024-12-25 14:14 UTC, cafedomancer commented on 04.class/file_operation.js
> +}
`FileOperation` クラスのいずれのメソッドも fs モジュールの関数に処理を委譲しているだけで、このクラスの存在意義がいまいち分からないです。

2025-02-20 11:37 UTC, bore-ko commented on 04.class/memo.js
> +class Memo extends FileOperation {
レビューありがとうございます！
extends を使うのをやめました。

2025-02-20 11:38 UTC, bore-ko commented on 04.class/memo.js
> +    this.displayMemos();
displayMemos() の処理を含めないようにしました。

2025-02-20 11:40 UTC, bore-ko commented on 04.class/memo.js
> +  }
クラスの外から呼び出せないようにプライベートメソッドにしました。
また、メソッドの定義順を参照順に合わせるようにしました。

2025-02-20 11:40 UTC, bore-ko commented on 04.class/memo.js
> +    this.file = "memos.json";
カプセル化しました。

2025-02-20 11:42 UTC, bore-ko commented on 04.class/memo.js
> +}
おっしゃる通り、Memo だと1件のデータのように見えますね。
Memo というクラス名を MemoApp に修正しました。

2025-02-20 11:42 UTC, bore-ko commented on 04.class/memo.js
> +      };
失礼しました。 throw err は削除しました。

2025-02-20 11:43 UTC, bore-ko commented on 04.class/memo.js
> +      let memos = await this.read(this.file);
ありがとうございます。再代入されない変数は const に書き換えました。

2025-02-20 11:54 UTC, bore-ko commented on 04.class/memo.js
> +      let listMemos = firstMemos.join("\n");
以下のように修正しました。
```js
const file_location = await this.#memoManager.read(this.#file_location);
...
const firstLines = memos.map((memo) => memo.lines[0]);
```

2025-02-20 11:55 UTC, bore-ko commented on 04.class/memo.js
> +      let listMemos = firstMemos.join("\n");
変数名は名詞形になるように修正しました。

2025-02-20 11:56 UTC, bore-ko commented on 04.class/memo.js
> +      let firstMemos = memos.map((memo) => memo.body[0]);
承知しました！firstMemos を firstLines  になおしました。

2025-02-20 11:58 UTC, bore-ko commented on 04.class/memo.js
> +    const { Select } = pkg;
そうですね、分割代入するのをやめました。

2025-02-20 11:59 UTC, bore-ko commented on 04.class/memo.js
> +import pkg from "enquirer";
pkg を enquirer に修正しました。

2025-02-20 12:00 UTC, bore-ko commented on 04.class/memo.js
> +      message: "Choose a note you want to see:",
気づきませんでした、、note を memo に修正しました。

2025-02-20 12:01 UTC, bore-ko commented on 04.class/memo.js
> +
不要は空白というのは、メモの中の空白でしょうか。こちら修正しました。

2025-02-20 12:02 UTC, bore-ko commented on 04.class/memo.js
> +    prompt.run().catch(console.error);
async/await を使うようにしました。

2025-02-20 12:02 UTC, bore-ko commented on 04.class/memo.js
> +  async add() {
await を使ってなかったですね。使うようにしました！

2025-02-20 12:03 UTC, bore-ko commented on 04.class/memo.js
> +    });
Promise に修正しました。

2025-02-20 12:03 UTC, bore-ko commented on 04.class/memo.js
> +    rl.on("line", (input) => {
なるほど。lines に対応するように line にしました。

2025-02-20 12:07 UTC, bore-ko commented on 04.class/memo.js
> +    });
こちら process.stdout を削除して、標準出力に出力されないようにしました。

<img width="279" alt="image" src="https://github.com/user-attachments/assets/d531fb1a-954f-49d3-a9be-2ea2071dadc8" />

2025-02-20 12:09 UTC, bore-ko commented on 04.class/memo.js
> +      memos.push({ body: lines });
ありがとうございます。
body は文字列が格納されるようなものに使うのですね。lines に変更しました。

2025-02-20 12:10 UTC, bore-ko commented on 04.class/memo.js
> +      let jsonMemos = JSON.stringify(memos, null, "\t");
タブはあまり使わないのですね。2スペースにしました。

2025-02-20 12:10 UTC, bore-ko commented on 04.class/memo.js
> +      this.write(this.file, jsonMemos);
await を使うようにしました。

2025-02-20 12:12 UTC, bore-ko commented on 04.class/file_operation.js
> +  async access(file) {
ありがとうございます。以下のように名前を修正しました。
access  → isAccess
file → file_location

2025-02-20 12:13 UTC, bore-ko commented on 04.class/file_operation.js
> +    }
catch でエラーを返すように修正しました。

2025-02-20 12:17 UTC, bore-ko commented on 04.class/memo.js
> +import * as readline from "readline";
参考コードにしたコードをそのまま使ったため、namespace import にしていました。
普通に default import にしました。`import readline from "readline";`

2025-02-20 12:20 UTC, bore-ko commented on 04.class/file_operation.js
> +      return JSON.parse(data);
ありがとうございます。
こちら迷ってました。FileOperation というクラス名だと、read メソッド で JSON.parse するのはやりすぎなのですね。JSON.parse するのをやめました。

2025-02-20 12:21 UTC, bore-ko commented on 04.class/file_operation.js
> +    }
throw err を削除しました。

2025-02-20 12:23 UTC, bore-ko commented on 04.class/file_operation.js
> +}
FileOperation クラスを MemoManager クラスという名前にして関数を追加しました。

2025-03-05 23:21 UTC, cafedomancer commented on 04.class/memo.js
> +  #file_location;
キャメルケースを使ってください。

2025-03-05 23:21 UTC, cafedomancer commented on 04.class/memo.js
> +    this.#argv = process.argv[2];
argv というのは argument vector のことで、コマンドライン引数のリストのことを意味します。特定のコマンドライン引数を扱うものに argv という名前を使うことはできません。

2025-03-05 23:21 UTC, cafedomancer commented on 04.class/memo.js
> +}
クラスはその名前と一致する (ケースは問わない) ファイルに 1 つずつ定義してください。

2025-03-05 23:21 UTC, cafedomancer commented on 04.class/memo.js
> +  }
public メソッド、private メソッドの順に定義してください。

2025-03-05 23:21 UTC, cafedomancer commented on 04.class/memo.js
> +  displayMemos() {
追加の処理も行うのだから display とは言えないと思います。

2025-03-05 23:21 UTC, cafedomancer commented on 04.class/memo.js
> +    } catch (err) {
try で囲む範囲が広すぎて、どこで例外が送出される想定なのか分からないです。例外が送出される想定の箇所に身を try で囲んでください。

2025-03-05 23:21 UTC, cafedomancer commented on 04.class/memo.js
> +      const isAccess = await this.#memoManager.isAccess(this.#file_location);
access は名詞なので、この名前だと「アクセスかどうか」という意味の分からない表現になってしまいます。

2025-03-05 23:21 UTC, cafedomancer commented on 04.class/memo.js
> +        console.log("There are no memo.");
are を使うなら memos だと思います。

2025-03-05 23:21 UTC, cafedomancer commented on 04.class/memo.js
> +        console.log("There are no memo.");
(`isAccess` がアクセス可能かどうかを表現する変数だとして) 「アクセス可能でないこと」と「メモがないこと」とがコードの字面上は紐づかないので、なぜこのような処理になっているのかを他の人が理解するのは難しいと思います。

2025-03-05 23:21 UTC, cafedomancer commented on 04.class/memo.js
> +      const file_location = await this.#memoManager.read(this.#file_location);
`this.#file_location` があるのに `file_location` が返ってくるメソッドを呼び出すって、何をしているのかぜんぜん分からないと思うんですが...。

2025-03-05 23:21 UTC, cafedomancer commented on 04.class/memo.js
> +      console.log(firstLines.join("\n"));
join しなくてもメモの 1 行目をループでそれぞれ出力すればいいだけだと思います。

2025-03-05 23:21 UTC, cafedomancer commented on 04.class/memo.js
> +          const index = this.index;
説明的になっているわけでもないし、他の箇所で使われているわけでもないので、変数に入れる意味がないと思います

2025-03-05 23:21 UTC, cafedomancer commented on 04.class/memo.js
> +            .filter((line) => line !== "")
質問ですが、空文字を読み飛ばしているのはなぜでしょうか？ メモの途中に空行を含むようなメモがあった場合、元のメモと異なるものが表示されてしまうと思いますよ。

2025-03-05 23:21 UTC, cafedomancer commented on 04.class/memo.js
> +      console.log(memos[prompt.index].lines.join("\n"));
enquirer の機能をうまく使えば index ではなく選択されたメモそのものを結果として取得できるはずです。

2025-03-05 23:21 UTC, cafedomancer commented on 04.class/memo_manager.js
> +  }
このあたりの処理は fs モジュールに処理をほぼ委譲しているだけで、クラスやメソッドにする意味がないですね。どこまでを `MemoApp` クラスの責務とし、どこからを `MemoManager` クラスの責務とするのか見直してください。ざっと見た感じでは、`MemoApp` クラスがメモの保存に関する詳細を知りすぎているように思います。

2025-03-05 23:21 UTC, cafedomancer commented on 04.class/memo_manager.js
> +export class MemoManager {
manager の意味するところが分からず、このクラスが何をするものなのかがよく分からないです。この後の変更に合わせて意味のある具体的な名前を付けてください。

2025-03-05 23:21 UTC, cafedomancer commented on 04.class/memo_manager.js
> +  readLines(rl) {
質問ですが、readline の interface (`readline.createInterface()` の戻り値) はなぜ引数として受け取っているんでしょうか？

2025-03-05 23:21 UTC, cafedomancer commented on 04.class/memo_manager.js
> +          resolve(false);
これだと resolve されたときの値のデータ型が else の場合と変わってしまいます。

2025-05-06 11:23 UTC, bore-ko commented on 04.class/memo.js
> +  #file_location;
失礼しました。キャメルケースを使うようにしました。

2025-05-06 11:26 UTC, bore-ko commented on 04.class/memo.js
> +    this.#argv = process.argv[2];
argument vector の略だったんですね。深く考えずに使っていました...。
argv を option に修正しました。

2025-05-06 11:27 UTC, bore-ko commented on 04.class/memo.js
> +}
クラス名とファイル名を一致するということでしょうか？同じにしました。

2025-05-06 11:28 UTC, bore-ko commented on 04.class/memo.js
> +  displayMemos() {
たしかにそうですね。OperateApp に変更しました！

2025-05-06 11:31 UTC, bore-ko commented on 04.class/memo.js
> +      console.log(memos[prompt.index].lines.join("\n"));
すみません、修正できているか分からないのですが、result を使うように修正しました。

2025-05-06 11:32 UTC, bore-ko commented on 04.class/memo_manager.js
> +  }
ありがとうございます！見直してみました。

2025-05-06 11:34 UTC, bore-ko commented on 04.class/memo_manager.js
> +export class MemoManager {
manager は曖昧でしたね。preparation 準備するというクラス名にしましたが、いかがでしょうか？

2025-05-06 11:35 UTC, bore-ko commented on 04.class/memo_manager.js
> +  readLines(rl) {
こちらも見直しました！

2025-05-06 11:36 UTC, bore-ko commented on 04.class/memo_manager.js
> +          resolve(false);
ありがとうございます。データ型を配列にするように統一しました！

2025-05-06 11:37 UTC, bore-ko commented on 04.class/memo.js
> +    } catch (err) {
try を修正しました。

2025-05-06 11:39 UTC, bore-ko commented on 04.class/memo.js
> +      const isAccess = await this.#memoManager.isAccess(this.#file_location);
おっしゃる通りですね。「アクセスかどうか」という意味だとよく分からないですね！
isMemo という名前にしました。

2025-05-06 11:41 UTC, bore-ko commented on 04.class/memo.js
> +        console.log("There are no memo.");
こちら memos に修正しました！

2025-05-06 11:42 UTC, bore-ko commented on 04.class/memo.js
> +        console.log("There are no memo.");
「アクセス可能でないこと」より「メモがないこと」の方が分かりやすいですね。ありがとうございます。修正しました。

2025-05-06 11:44 UTC, bore-ko commented on 04.class/memo.js
> +      console.log(firstLines.join("\n"));
なるほど。join をするのをやめました。

2025-05-06 11:44 UTC, bore-ko commented on 04.class/memo.js
> +          const index = this.index;
気づきませんでした。修正しました。

2025-05-06 11:45 UTC, bore-ko commented on 04.class/memo.js
> +            .filter((line) => line !== "")
勘違いしていました。空行も含めて表示するようにしました。

2025-05-06 11:58 UTC, bore-ko commented on 04.class/memo.js
> +      const file_location = await this.#memoManager.read(this.#file_location);
失礼しました。修正しました。

2025-05-11 04:15 UTC, bore-ko commented on 04.class/memo.js
> +  }
ありがとうございます！public メソッド、private メソッドの順に定義しました！

2025-05-12 23:50 UTC, cafedomancer commented on 04.class/memo_app.js
> +  #MemoPreparation;
変数名には lower camel case を使ってください。

2025-05-12 23:50 UTC, cafedomancer commented on 04.class/memo_app.js
> +  OperateApp() {
メソッド名には lower camel case を使ってください。それから、`MemoApp` と `OperateApp()` で app が重複しているように思います。

2025-05-12 23:50 UTC, cafedomancer commented on 04.class/memo_app.js
> +    const readedMemos = await fs.readFile(this.#fileLocation, "utf8");
この時点で読み込んだものはまだメモとして解釈できるオブジェクトではなんじゃないですかね。ただの JSON 文字列だと思います。それに memos と付けるのは妥当ではないような気がしました。後続の memos と区別するために readed を付けているのだと思いますが、それは本質的ではないし、区別も分かりづらくなっています。

2025-05-12 23:50 UTC, cafedomancer commented on 04.class/memo_app.js
> +    if (readedMemos === "[]") {
JSON 文字列をチェックしているのは良くない気が...。配列なりオブジェクトなり、データとして意味のある形になったものをチェックに使ってください。

2025-05-12 23:50 UTC, cafedomancer commented on 04.class/memo_app.js
> +      const response = await prompt.run();
この名前だと何が返ってくるのか分からないです。中身を表す具体的な名前を付けましょう。

2025-05-12 23:50 UTC, cafedomancer commented on 04.class/memo_app.js
> +      const deleteMemo = await prompt.run();
delete は動詞なので、名詞である memo を修飾することはできないです。

2025-05-12 23:50 UTC, cafedomancer commented on 04.class/memo_app.js
> +      const index = deleteMemo - 1;
なんで memo に対して - 1 という演算ができるんですかね。命名が破綻しているように思います。

2025-05-12 23:50 UTC, cafedomancer commented on 04.class/memo_app.js
> +    const jsonMemos = JSON.stringify(memos, null, "  ");
JSON のインデントをスペース 2 つにしたいなら `"  "` よりも `2` を渡すほうが分かりやすいと思います。空白文字だといくつかあるか確認しづらいからです。それと、`jsonMemos` に格納されるのはメモではなく JSON 文字列なので、json ではなく memos が主体となるような名前は妥当ではなさそうです。

2025-05-12 23:50 UTC, cafedomancer commented on 04.class/memo_app.js
> +    let isMemo;
`isMemo` という変数名では、どういう情報が格納されているのか分からないです。「メモであるかどうか」を格納したいわけではないでしょう。

2025-05-12 23:50 UTC, cafedomancer commented on 04.class/memo_app.js
> +    }
`isMemo` のようなフラグを使って処理を制御するのではなく、ファイルが存在しなければ `[]` を含むような JSON ファイルを作るようにすればいいんじゃないですかね。そうすれば、`isMemo` による分岐も不要になるはずです。

2025-05-12 23:50 UTC, cafedomancer commented on 04.class/memo_app.js
> +    } catch (err) {
コメントし忘れていましたが、変数名に省略形を使うのは避けてください。err ぐらいならすぐ分かるんですが、他の省略形だと読み手が意味を推測する必要があるからです。習慣として、省略形を使わないことを身に付けてください。

2025-05-12 23:50 UTC, cafedomancer commented on 04.class/memo_app.js
> +    }
意味のない例外処理に見えます。catch しなければ例外が上位に伝播されて、上位でも catch されなければ標準エラー出力に例外の内容が出力されるからです。

2025-05-12 23:50 UTC, cafedomancer commented on 04.class/memo_app.js
> +const memo = new MemoApp();
この変数に格納されるのはメモではないと思いますよ。

2025-05-12 23:50 UTC, cafedomancer commented on 04.class/memo_preparation.js
> +export class MemoPreparation {
クラス名には動作の主体となるような名前を付けてください。app や manager は動作の主体とみなせますが、preparation (準備という行為そのもの) は動作の主体とみなせないと思います。

2025-05-12 23:50 UTC, cafedomancer commented on 04.class/memo_preparation.js
> +    });
Promise として扱う必要が全くないような。非同期処理は出てきていないと思いますよ。

2025-05-12 23:50 UTC, cafedomancer commented on 04.class/memo_preparation.js
> +  referencePrompt(memos) {
メソッド名は動詞始まりにしてください。

2025-05-12 23:50 UTC, cafedomancer commented on 04.class/memo_preparation.js
> +  }
質問なんですが、参照の prompt には footer (というかメモの中身) が表示されていて、削除の prompt には表示されていないのはなぜでしょうか？

2025-05-12 23:50 UTC, cafedomancer commented on 04.class/memo_preparation.js
> +    });
readline の Promise API を使ってください。

2025-05-12 23:50 UTC, cafedomancer commented on 04.class/memo_preparation.js
> +new MemoPreparation();
import されるクラスにトップレベルの処理を持たせてはダメです。import されたときにトップレベルの処理が動作してしまうからです。

2025-05-12 23:50 UTC, cafedomancer commented on 04.class/memo_preparation.js
> +}
このクラスの処理はメモアプリに付随する雑多な処理をまとめただけのクラスで、クラスにする意味が正直ないと思います。クラスは基本的の状態とそれに関する振る舞いを持つものですが、このクラスは状態も持っていません。それも関係してか、`MemoPreparation` のような抽象的な名前しか付けられていないのかもしれません。どう直したらよいか、どの部分をクラスにするか (あるいはしないか) はまず自分で考えてやってみてください。

2025-06-16 14:59 UTC, bore-ko commented on 04.class/memo_app.js
> +  #MemoPreparation;
失礼しました。lower camel case を使うようにしました。

2025-06-16 15:35 UTC, bore-ko commented on 04.class/memo_app.js
> +  OperateApp() {
ありがとうございます！MemoApp と Operate() に修正しました。

2025-06-16 15:40 UTC, bore-ko commented on 04.class/memo_app.js
> +    const readedMemos = await fs.readFile(this.#fileLocation, "utf8");
おっしゃる通り readedMemos ではないですね。jsonList に修正しました。

2025-06-16 15:41 UTC, bore-ko commented on 04.class/memo_app.js
> +    if (readedMemos === "[]") {
JSON 文字列をチェックしているのは良くないんですね。parse してからチェックするようにしました。

2025-06-16 15:44 UTC, bore-ko commented on 04.class/memo_app.js
> +      const response = await prompt.run();
response は曖昧でした。中身を表せる具体的な名前を付けるようにします。

2025-06-16 15:45 UTC, bore-ko commented on 04.class/memo_app.js
> +      const deleteMemo = await prompt.run();
deletionIndex にしました。いかがでしょうか。

2025-06-16 15:46 UTC, bore-ko commented on 04.class/memo_app.js
> +      const index = deleteMemo - 1;
意味の分からないことをしていましたので修正しました。

2025-06-16 15:47 UTC, bore-ko commented on 04.class/memo_app.js
> +    const jsonMemos = JSON.stringify(memos, null, "  ");
jsonList = JSON.stringify(memos, null, 2) に修正しました！

2025-06-16 15:48 UTC, bore-ko commented on 04.class/memo_app.js
> +    let isMemo;
なるほど、確かにそうですね。

2025-06-16 16:07 UTC, bore-ko commented on 04.class/memo_app.js
> +    }
ありがとうございます！思いつきませんでした。教えていただいたように修正しました。

2025-06-16 16:08 UTC, bore-ko commented on 04.class/memo_app.js
> +    } catch (err) {
承知しました。error に修正しました！

2025-06-16 16:08 UTC, bore-ko commented on 04.class/memo_app.js
> +    }
なるほど、書く必要ないんですね。削除しました。

2025-06-16 16:10 UTC, bore-ko commented on 04.class/memo_app.js
> +const memo = new MemoApp();
memo を memoApp にしました！

2025-06-17 12:12 UTC, bore-ko commented on 04.class/memo_preparation.js
> +export class MemoPreparation {
クラス名を Prompt に修正しました。

2025-06-17 12:13 UTC, bore-ko commented on 04.class/memo_preparation.js
> +    });
おしゃる通りですので修正しました。

2025-06-17 12:14 UTC, bore-ko commented on 04.class/memo_preparation.js
> +  referencePrompt(memos) {
referencePrompt を refer に修正しました！

2025-06-17 12:18 UTC, bore-ko commented on 04.class/memo_preparation.js
> +  }
[メモアプリコマンドライン版](https://bootcamp.fjord.jp/pages/238#:~:text=%E5%89%8A%E9%99%A4-,%E9%81%B8%E3%82%93%E3%81%A0%E3%83%A1%E3%83%A2%E3%81%8C%E5%89%8A%E9%99%A4%E3%81%95%E3%82%8C%E3%82%8B%E3%80%82,-%24%20./memo.js%20%2Dd) に削除のときはメモの中身が書かれていなかったので実装しませんでした。
考えてみると、メモの中身を表示した方が親切だと思ったので footer を追加しました。

2025-06-17 12:20 UTC, bore-ko commented on 04.class/memo_preparation.js
> +    });
書き方を修正しました。

2025-06-17 12:20 UTC, bore-ko commented on 04.class/memo_preparation.js
> +new MemoPreparation();
ありがとうございます。こちら削除しました。

2025-06-17 12:22 UTC, bore-ko commented on 04.class/memo_preparation.js
> +}
考えてみました！お手すきの際にご確認いただけますと幸いです。

2025-06-20 00:23 UTC, cafedomancer commented on 04.class/memo_app.js
> +export class MemoApp {
default export でよいと思います。他に export しているものが無いからです。

2025-06-20 00:23 UTC, cafedomancer commented on 04.class/memo_app.js
> +    }
この処理が複数のメソッドで重複しているので共通化して欲しいです 🙏

2025-06-20 00:23 UTC, cafedomancer commented on 04.class/memo_app.js
> +    const jsonList = await fs.readFile(this.#fileLocation, "utf8");
この名前だと JSON のリスト（JSON 文字列の配列かなにか）にも解釈できます。が、そうではないので単に `json` とかで良いんじゃないですかね。

2025-06-20 00:23 UTC, cafedomancer commented on 04.class/memo_app.js
> +    }
この処理も複数のメソッド間で重複しています。

2025-06-20 00:23 UTC, cafedomancer commented on 04.class/memo_app.js
> +    jsonList = JSON.stringify(memos, null, 2);
この変数に再代入する（変数を使い回す）必要はないんじゃないですかね？

2025-06-20 00:23 UTC, cafedomancer commented on 04.class/memo_app.js
> +    const inputLines = await this.#standardInput.readLines();
標準入力から読み込んでいることは使っているメソッドから分かるので input はなくても良いかもです。一行下の lines と名前を揃えたいです。

2025-06-20 00:23 UTC, cafedomancer commented on 04.class/prompt.js
> +export class Prompt {
このクラス名だと汎用的に使える何かに見えますが、メモアプリに特化した処理であることを考えると、名前が汎用的すぎる気がします。

2025-06-20 00:23 UTC, cafedomancer commented on 04.class/prompt.js
> +    return new enquirer.Select({
このクラスでプロンプトを抽象的に扱う設計にしたいのだとすると、このクラスで内部的に使われている enquirer のオブジェクトがこのクラスの外に出ていくのは良くない設計ですね。このクラス以外でも enquirer への依存が発生し、このクラスでプロンプトを抽象的に扱うという目的が達成できなくなるからです。

2025-06-20 00:23 UTC, cafedomancer commented on 04.class/memo_app.js
> +      const referencedMemo = await prompt.run();
他の部分で memo と使われているところは `{ lines: ... }` のようなオブジェクトが入っているのに、ここだけ string が入っているような気がします :eyes:

2025-06-20 00:23 UTC, cafedomancer commented on 04.class/standard_input.js
> +export class StandardInput {
標準入力というのは入力を受け付けるための入り口で、それ自体が何か処理を持っているわけではないので、このようなクラスが定義されているのはだいぶ違和感があります。また、`StarndardInput` という名前なのに、中に定義されているのは readline の処理をラップしたものだけで、標準入力とは直接的に関係のない処理が定義されているように見えます。

2025-07-20 12:02 UTC, bore-ko commented on 04.class/memo_app.js
> +export class MemoApp {
ありがとうございます。
default export するようにしました。

2025-07-20 12:03 UTC, bore-ko commented on 04.class/memo_app.js
> +    }
こちらの重複を関数にしました！

2025-07-20 12:04 UTC, bore-ko commented on 04.class/memo_app.js
> +    const jsonList = await fs.readFile(this.#fileLocation, "utf8");
json に修正しました。

2025-07-20 12:04 UTC, bore-ko commented on 04.class/memo_app.js
> +    }
ありがとうございます。こちらの重複も関数化しました！

2025-07-20 12:10 UTC, bore-ko commented on 04.class/memo_app.js
> +    jsonList = JSON.stringify(memos, null, 2);
気付かず再代入していました。失礼しました。

2025-07-20 12:10 UTC, bore-ko commented on 04.class/memo_app.js
> +    const inputLines = await this.#standardInput.readLines();
名前を揃えるようにしました。
`{ lines: lines });`

2025-07-20 12:12 UTC, bore-ko commented on 04.class/prompt.js
> +export class Prompt {
なるほど、MemoPrompt に修正しました。

2025-07-20 12:14 UTC, bore-ko commented on 04.class/prompt.js
> +    return new enquirer.Select({
おしゃる通り、 enquirer のオブジェクトを返していますね。外に出ないように修正しました！

2025-07-20 12:15 UTC, bore-ko commented on 04.class/memo_app.js
> +      const referencedMemo = await prompt.run();
こちらも確認しました。オブジェクトを返すようにしました。

2025-07-20 12:21 UTC, bore-ko commented on 04.class/standard_input.js
> +export class StandardInput {
ありがとうございます。こちらクラスにするのをやめました。

2025-07-23 00:39 UTC, cafedomancer commented on 04.class/memo_app.js
> +      throw new Error();
メッセージがない `Error` を throw しても何のエラーなのか分からないです。というのと、エラーがあったときに何をするか（今回でいえばメッセージの出力）を決めるのは関数の呼び出し側がやることです。

2025-07-23 00:39 UTC, cafedomancer commented on 04.class/memo_app.js
> +  async #createMemoObjct(fileLocation) {
typo してます。

2025-07-23 00:39 UTC, cafedomancer commented on 04.class/memo_app.js
> +    }
例外は適切にハンドリングしてください。今の実装だと例外が一律に握り潰されています 🙅‍♀️

2025-07-23 00:39 UTC, cafedomancer commented on 04.class/memo_app.js
> +      const referencedMemo = await this.#memoPrompt.selectMemo(memos, "see");
reference と select で表現がズレているような。refer という処理に合わせるにしてもズレている気がします。

2025-07-23 00:39 UTC, cafedomancer commented on 04.class/memo_app.js
> +    });
function 式ではなくアロー関数を使ってください。https://github.com/airbnb/javascript?tab=readme-ov-file#arrows--use-them

2025-07-23 00:39 UTC, cafedomancer commented on 04.class/memo_app.js
> +      return memo !== deletionMemo;
オブジェクト同士は単純には比較できないような...。

2025-07-23 00:39 UTC, cafedomancer commented on 04.class/memo_app.js
> +    let memos = JSON.parse(json);
再代入されない変数は const で宣言してください。https://github.com/airbnb/javascript?tab=readme-ov-file#references

2025-07-23 00:39 UTC, cafedomancer commented on 04.class/memo_app.js
> +    memos.push({ lines: lines });
プロパティ名と値が同じ時は省略記法を使ってください。

2025-07-23 00:39 UTC, cafedomancer commented on 04.class/memo_prompt.js
> +  async selectMemo(memos, status) {
受け取っているのは status ではないような。

2025-07-23 00:39 UTC, cafedomancer commented on 04.class/memo_prompt.js
> +}
このクラス、状態を持っていないのでクラスにする意味がないです。

2025-08-05 14:39 UTC, bore-ko commented on 04.class/memo_app.js
> +      throw new Error();
ありがとうございます。
エラーのメッセージを渡して、呼び出す側の関数で出力するように修正しました。

2025-08-05 14:39 UTC, bore-ko commented on 04.class/memo_app.js
> +  async #createMemoObjct(fileLocation) {
大変失礼しました 🙇‍♂️

2025-08-05 14:41 UTC, bore-ko commented on 04.class/memo_app.js
> +    }
例外をハンドリングするようにしました！

2025-08-05 14:42 UTC, bore-ko commented on 04.class/memo_app.js
> +      const referencedMemo = await this.#memoPrompt.selectMemo(memos, "see");
ありがとうございます。
referencedMemo を selectedMemo に修正しました。

2025-08-05 14:43 UTC, bore-ko commented on 04.class/memo_app.js
> +    });
アロー関数にしました。URL添付もありがとうございます！

2025-08-05 14:44 UTC, bore-ko commented on 04.class/memo_app.js
> +      return memo !== deletionMemo;
そうなのですね。こちら Object.is() を使って比較するようにしました。

2025-08-05 14:47 UTC, bore-ko commented on 04.class/memo_app.js
> +    let memos = JSON.parse(json);
勘違いしておりました...。
このあとの push で再代入されると思っていました。末尾に追加するのと再代入は別ものなのですね。

2025-08-05 14:47 UTC, bore-ko commented on 04.class/memo_app.js
> +    memos.push({ lines: lines });
省略記法を使って簡潔になりました！

2025-08-05 14:51 UTC, bore-ko commented on 04.class/memo_prompt.js
> +  async selectMemo(memos, status) {
命名がいつもズレてまして、お手数おかけしてすみません 🙇‍♂️
 status → action はいかがでしょうか？

2025-08-05 14:55 UTC, bore-ko commented on 04.class/memo_prompt.js
> +}
こちら関数1つなのでクラスにするのをやめました。

2025-08-28 15:37 UTC, cafedomancer requested changes

2025-08-28 15:37 UTC, cafedomancer commented on 04.class/memo_app.js
> +    }
一律に握りつぶされているという問題が解決していないです。

2025-08-28 15:37 UTC, cafedomancer commented on 04.class/memo_app.js
> +      return memo !== deletionMemo;
`Object.is()` でも比較はできないと思いますよ。https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Object/is#%E8%A7%A3%E8%AA%AC

2025-08-28 15:37 UTC, cafedomancer commented on 04.class/memo_app.js
> +      return console.error(error.message);
`console.error` は戻り値のない関数なので、その結果を `return` しても意味がないです。

2025-08-28 15:37 UTC, cafedomancer commented on 04.class/memo_app.js
> +  async #createMemoObject(fileLocation) {
前回コメントし忘れていたのかもですが、create という名前だと登録とちょっと紛らわしいような気がします。ファイルから読み込んでオブジェクトを生成して返しているのが分かるような名前にすると良いと思います。

2025-08-28 15:37 UTC, cafedomancer commented on 04.class/memo_app.js
> +      });
アロー関数の簡潔文体を使ってください。https://github.com/airbnb/javascript?tab=readme-ov-file#arrows--implicit-return

2025-08-28 15:37 UTC, cafedomancer commented on 04.class/memo_app.js
> +    await fs.writeFile(this.#fileLocation, jsonMemo, "utf8");
ファイルから読み込みはメソッドになっているのに、ファイルへの書き込みはメソッドになってないのは、処理の抽象性に一貫性がなさそうです。add と処理が重複している点も気になります。

2025-09-15 13:39 UTC, bore-ko commented on 04.class/memo_app.js
> +      return console.error(error.message);
ありがとうございます！
console.error と return を別々に書くように修正しました。

2025-09-15 13:41 UTC, bore-ko commented on 04.class/memo_app.js
> +  async #createMemoObject(fileLocation) {
こちら buildMemoObjectFromFile に修正しました。

2025-09-15 13:42 UTC, bore-ko commented on 04.class/memo_app.js
> +      });
アロー関数の簡潔文体に修正しました。
URLもありがとうございます！

2025-09-15 13:43 UTC, bore-ko commented on 04.class/memo_app.js
> +    await fs.writeFile(this.#fileLocation, jsonMemo, "utf8");
おっしゃる通り一貫性がなかったですね。
メソッドにまとめるようにしました！

2025-10-04 00:39 UTC, cafedomancer commented on 04.class/memo_app.js
> +  }
operate から参照されているメソッドをまず定義し、それらのメソッドから参照されているメソッドをその後に定義するほうが、プログラム全体を見る時に理解しやすいかなーと思いました。後者のメソッドが先に定義されていると、上から読んだ時に全体像よりも先に詳細が目に入ってきてしまって、メソッド呼び出しのどの深さのところを今見ているかが分かりづらいような気がします :eyes: ぼくが実際にこのコードを読む時も、上に行ったり下に行ったりして見なくちゃいけなくて、読むのが結構大変だなという実感があります。

2025-10-04 00:39 UTC, cafedomancer commented on 04.class/memo_app.js
> +    }
https://github.com/bore-ko/js-practices/pull/4#discussion_r2307763638 の内容が反映されてなさそうです :eyes: 例外の握り潰しやその問題点については、非同期処理のプラクティスでコメントしていると思うので、そちらの内容を再確認してみてください 🙏 以下のあたりは問題なく処理されているように見えます！　
https://github.com/bore-ko/js-practices/blob/9d555cb1fa3df08980c00ea9425cbca8db9a2a0c/04.class/memo_app.js#L118-L122

2025-10-04 00:39 UTC, cafedomancer commented on 04.class/memo_app.js
> +    const memos = JSON.parse(json);
ファイルの読み込みは、他の箇所では `#buildMemoObjectFromFile` が使われているのにここでは使われていないです :eyes: DRY になってないと、ファイルの読み込みに関して変更が発生したときに、修正漏れが発生してしまう可能性があります。

2025-10-04 00:39 UTC, cafedomancer commented on 04.class/memo_app.js
> +      throw new Error("There are no memos.");
例外のメッセージに、例外そのものに関するメッセージじゃなくて、メモアプリとしてコンソールに表示するメッセージが含まれてしまっています。例外を捕捉したときにどのようなメッセージを出力するか (あるいは何もしないのか) を決めるのは、例外を捕捉する側が決めることです :eyes: ここでメッセージを入れるなら「ファイルが無いこと」を入れるべきじゃないかなーと思いました。メッセージだけではないところで `Error` の識別性を高めるなら、それ用の `Error` のサブクラスを定義するのもよいと思います。

2025-10-04 00:39 UTC, cafedomancer commented on 04.class/memo_app.js
> +  async #buildMemoObjectFromFile(fileLocation) {
`#writeMemoToFile` と名前に対称性を持たせるなら build ではなく read にしたほうが良さそうです :eyes:

2025-10-04 00:39 UTC, cafedomancer commented on 04.class/memo_app.js
> +    } else {
メモが 0 件であること自体は異常なケースではなく、メモアプリとしては普通に存在しうる状態なので、例外として扱わないほうがいいかなーと思います。呼び出し側にも、本来は不要なはずの例外処理が増えてしまって、処理が煩雑になってしまいます。

2025-10-04 00:39 UTC, cafedomancer commented on 04.class/memo_app.js
> +    return [memos[prompt.index], prompt.index];
`#selectMemo` を実行すると、メモとその添え字を含む配列が返ってくるのは、コードを読む側にとってはかなり見通しづらい挙動だと思います :eyes: これをやるくらいなら、メモのオブジェクトに ID を持たせて、プログラム中でのメモの識別はその ID でするほうが見通しが良くなると思います。

2026-02-07 08:26 UTC, bore-ko commented on 04.class/memo_app.js
> +  }
ありがとうございます！
メソッドの定義順を修正しました。
[1731c14](https://github.com/bore-ko/js-practices/pull/4/commits/1731c1460aaf7d46b80a34c758fddc6c7db852c5)

2026-02-07 08:27 UTC, bore-ko commented on 04.class/memo_app.js
> +    }
失礼しました。
コードもありがとうございます。
こちらで修正しました。
[dda0d2c](https://github.com/bore-ko/js-practices/pull/4/commits/dda0d2c754a15b00fbd068b46e57d54a6371aa92)

2026-02-07 08:30 UTC, bore-ko commented on 04.class/memo_app.js
> +    const memos = JSON.parse(json);
おっしゃる通りですね。こちらでも使うようにしました。
[14e92e1](https://github.com/bore-ko/js-practices/pull/4/commits/14e92e1ae963383acb8230efc91a46c9d81b05fd)

2026-02-07 08:33 UTC, bore-ko commented on 04.class/memo_app.js
> +      throw new Error("There are no memos.");
メッセージを "File not found." に修正しました。
[0f9da7d](https://github.com/bore-ko/js-practices/pull/4/commits/0f9da7dbf356532b8e6636f1528d914efed3b8c0)

2026-02-07 08:33 UTC, bore-ko commented on 04.class/memo_app.js
> +  async #buildMemoObjectFromFile(fileLocation) {
ありがとうございます。read に修正しました。
 [17d3219](https://github.com/bore-ko/js-practices/pull/4/commits/17d32196a366c9fe5b36812f1344693d22943215)

2026-02-07 08:34 UTC, bore-ko commented on 04.class/memo_app.js
> +    } else {
例外として扱わないようにしました。
[990303f](https://github.com/bore-ko/js-practices/pull/4/commits/990303f6e26d9b0ca469d2594078e7daa1e23901)

2026-02-07 08:38 UTC, bore-ko commented on 04.class/memo_app.js
> +    return [memos[prompt.index], prompt.index];
なるほど。ID を持たせるようしたほうが読みやすくなりました。
[73e828c](https://github.com/bore-ko/js-practices/pull/4/commits/73e828c714947335f6f322af4dc02d7845da25ea)

2026-02-19 23:25 UTC, cafedomancer commented on 04.class/memo_app.js
> +      if (error.message === "File not found.") {
`error` は必ずしもプロパティアクセスできる値とは限らないので、そのような例外を捕捉した場合は `error.message` の部分でプロパティアクセスに対するエラーが起きてしまいます。

2026-02-19 23:25 UTC, cafedomancer commented on 04.class/memo_app.js
> +      throw error;
catch 内の処理が、早期リターンが使われていたり else が使われていたりして一貫性がないので、統一したほうがよいと思います。

2026-02-19 23:25 UTC, cafedomancer commented on 04.class/memo_app.js
> +    } catch (error) {
`selectedMemo` のスコープ的に `filteredMemos` を try の中で充足しているのだと思いますが、一連の try...catch で処理したいのはあくまで `await this.#selectMemo(memos, "delete")` の部分なので、`selectedMemo` を let で定義して、filter するのはその後にすると分かりやすいんじゃないかなと思いました。refer のほうはシンプルなので今のままでもよいと思いますが。一貫性を持たせるなら delete と合わせてもよちお思います。

2026-02-22 10:25 UTC, bore-ko commented on 04.class/memo_app.js
> +      if (error.message === "File not found.") {
ありがとうございます。非同期処理のプラクティスを参考に修正しました。

2026-02-22 10:26 UTC, bore-ko commented on 04.class/memo_app.js
> +      throw error;
おっしゃる通りですね。統一するようにしました。

2026-02-22 10:27 UTC, bore-ko commented on 04.class/memo_app.js
> +    } catch (error) {
try...catch でやりすぎだったのですね。try...catch は await の部分だけにして、filter はその後でするように修正しました。

2026-02-27 22:43 UTC, cafedomancer commented on 04.class/memo_app.js
> +      if (error.message === "File not found.") {
確認ですが、ff5ed988777af289df700ef7e1bbcc87c458e01d で `#checkExistenceMemo()` が無くなっているのはなぜですかね？ メソッドを無くそうというコメントはしていないので、なぜこの対応になったのかが気になりました。

2026-02-28 05:14 UTC, bore-ko commented on 04.class/memo_app.js
> +      if (error.message === "File not found.") {
ご確認ありがとうございます。
`#checkExistenceMemo()`を前回修正して一行になったため無くしましたが、
```js
  async #checkExistenceMemo(fileLocation) {
    await fs.access(fileLocation);
  }

# エラー処理を呼び出し側で対応するようにしたため
```
メソッドにして名前を付けた方が分かりやすいのと、複数箇所から呼び出しているため今後の修正を考えるとメソッドの方がいいかと考え修正をしました。
[aca0af5](https://github.com/bore-ko/js-practices/pull/4/commits/aca0af503c5062741d093103bb84bfc6d0d30809)

2026-03-05 22:45 UTC, cafedomancer commented on 04.class/memo_app.js
> +      if (error.message === "File not found.") {
> `#checkExistenceMemo()`を前回修正して一行になったため無くしましたが、

分かりました。それでよいと思います。

> メソッドにして名前を付けた方が分かりやすいのと、複数箇所から呼び出しているため今後の修正を考えるとメソッドの方がいいかと考え修正をしました。
[aca0af5](https://github.com/bore-ko/js-practices/pull/4/commits/aca0af503c5062741d093103bb84bfc6d0d30809)

https://github.com/bore-ko/js-practices/pull/4#discussion_r2866523921 のコメントでは純粋に理由を確認しているだけなので、修正は取り消してもらえると 🙏

2026-03-07 06:08 UTC, bore-ko commented on 04.class/memo_app.js
> +      if (error.message === "File not found.") {
失礼しました。修正を取り消しました！

2026-03-07 22:07 UTC, cafedomancer approved these changes

2026-03-08 03:20 UTC, merged